### ISSUE TITLE
2nd RPI2 Instance on Multihost

### ISSUE THREAD

**Issue by MSal-RPI4** [iobroker-community-adapters/ioBroker.rpi2#100]
**Describe the bug**  
Trying to install 2nd rpi2 instance on fully functioning multihost (master/slave).

**To Reproduce**  
Master instance working fine, but continue getting error message below when trying to add 2nd instance for slave.

**Expected behavior**  
Getting error message below even though slave was specifically selected as host.

**Screenshots & Logfiles**  
$ iobroker add rpi2 auto --host iobroker-master
host.iobroker-master error: this adapter does not allow multiple instances on one host
ERROR: Process exited with code 21

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: Debian 11 (bullseye)

**Comment by Apollon77** [comment]
You need to choose the slave in Admin in the selection on top .. then add the instance and it will work

**Comment by MSal-RPI4** [comment]
Thanks, that's exactly what I had tried numerous times ... but as said didn't work, always got the same error message since it continued to refuse slave selection.

However, I did find another "workaround" in the forum, which works just fine: Manually moved 1st instance from master to slave, so that subsequent installation of 2nd instance was installed successfully on master ;-)

**Comment by Apollon77** [comment]
Just that we understand oursefl. I NO NOT mean the "Host "selection in the "create instace dialog ... I Mean the host selection in "Instances" page on the top bar  ...

**Comment by MSal-RPI4** [comment]
That's correct, essentially tried every combination, but nothing worked ... except the "workaround".
