### ISSUE TITLE
Installation schlägt fehl

### ISSUE THREAD

**Issue by bobmorane77** [iobroker-community-adapters/ioBroker.rpi2#112]
Log:
12 verbose cwd /opt/iobroker
13 verbose Linux 5.10.63-v7l+
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-exact" "--loglevel" "error" "iobroker.rpi2@1.3.2"
15 verbose node v14.19.0
16 verbose npm  v6.14.16
17 error Unexpected end of JSON input while parsing near '...----\r\nVersion: Open'
18 verbose exit [ 1, true ]

js-controller 4.0.15
auf einem raspi 4b

**Comment by Apollon77** [comment]
try to clean npm cache ... it is not an issue of the adapter package, I was able to install it
