### ISSUE TITLE
USB hard drive

### ISSUE THREAD

**Issue by nimda2** [iobroker-community-adapters/ioBroker.rpi2#118]
Hi, would it be possible to read out a connected USB hard drive in addition to the SD card?

Unfortunately, so far you can only see the SD memory.

**Comment by Apollon77** [comment]
In fact all commands that are executed are listed in io.package file, e.g. for sd card https://github.com/iobroker-community-adapters/ioBroker.rpi2/blob/master/io-package.json#L299-L323

In fact find out the commands you need for a usb hard drive and we could add them

**Comment by nimda2** [comment]
For me its 
df /dev/sda1 
for mounted extern USB Hard Drive

**Comment by SirFlour** [comment]
yes that would be great. i just changed from sd card to usb drive and so it would be cool to see the usb drive infos :) i am happy to test :)

**Comment by nimda2** [comment]
`    "sdcard": {
      "sdcard_root_total": {
        "command": "df /",
        "regexp": "\\S+\\s+(\\d+).*\\/$",
        "post": "$1/1024",
        "multiline": true
      },
      "sdcard_boot_total": {
        "command": "df /boot",
        "regexp": "\\S+\\s+(\\d+).*\\/boot$",
        "post": "$1/1024",
        "multiline": true
      },
      "sdcard_usb_total": {
        "command": "df /dev/sda1",
        "regexp": "\\S+\\s+(\\d+).*\\/dev/sda1$",
        "post": "$1/1024",
        "multiline": true
      },
      "sdcard_root_used": {
        "command": "df /",
        "regexp": "\\S+\\s+\\d+\\s+(\\d+).*\\/$",
        "post": "$1/1024",
        "multiline": true
      },
      "sdcard_boot_used": {
        "command": "df /boot",
        "regexp": "\\S+\\s+\\d+\\s+(\\d+).*\\/boot$",
        "post": "$1/1024",
        "multiline": true
      },
      "sdcard_usb_used": {
        "command": "df /dev/sda1",
        "regexp": "\\S+\\s+\\d+\\s+(\\d+).*\\/dev/sda1$",
        "post": "$1/1024",
        "multiline": true
      }`

now it works for me
![Screenshot 2022-04-23 194112](https://user-images.githubusercontent.com/46486386/164929419-97819dbb-3dba-46f5-b2a8-878a77a104f7.png)

**Comment by Damrak2022** [comment]
Ich wäre es eine SSD-Festplatte an df /dev/sda2
