### ISSUE TITLE
Installation stops with ERROR:31

### ISSUE THREAD

**Issue by therod666** [iobroker-community-adapters/ioBroker.rpi2#12]
Hello
installing on Rpi4 with admin 3.7.7 and node 10.18.1. ends with Error Code 31.
"host.ioBroker Adapter does not support current os. Required one of linux. Actual platform: linux"

[Error31_rpi4.docx](https://github.com/iobroker-community-adapters/ioBroker.rpi2/files/4093315/Error31_rpi4.docx)

the following command i used before install the adapter:
`sudo apt-get install -y build-essential python`

**Comment by Apollon77** [comment]
which js-controller is used?

**Comment by therod666** [comment]
the latest 2.2.7

**Comment by Apollon77** [comment]
This actuallay seems to be a bug in JS controller ... will be fixed in coming 2.2.8

**Comment by therod666** [comment]
okay, I'll wait thx
