### ISSUE TITLE
SD-Card: error return: Cannot evaluate: Filesystem 1K-blocks Used Available Use% Mounted onoverlay

### ISSUE THREAD

**Issue by OneCreek** [iobroker-community-adapters/ioBroker.rpi2#127]
rpi2.0: Version: v1.3.2

Error Message when SD-Card Active in Instance:
`rpi2.0 | 2022-06-17 21:55:42.232 | error | Cannot evaluate: Filesystem 1K-blocks Used Available Use% Mounted onoverlay 15018504 6448816 7924604 45% //1024`
[2022-06-16a1 rpi2.txt](https://github.com/iobroker-community-adapters/ioBroker.rpi2/files/8931162/2022-06-16a1.rpi2.txt) _unfortunately, the end of the lines in the log are cut..._

ioBroker runns in a docker container on RaspberryPi.

The 45% memory are correct if i check in the host system via `df`.

**Comment by JiroMusik** [comment]
How can I disable that message?

**Comment by David91919** [comment]
Same issue here with latest adapter

**Comment by daOlli** [comment]
Same issue: Cannot evaluate: Filesystem 1K-blocks Used Available Use% Mounted onoverlay 959783680 11035760 899919828 2% //1024

**Comment by Zygonz** [comment]
Gleiches Problem hier mit dem neuesten Adapter

**Comment by erwinberlin** [comment]
Same problem here!

**Comment by djamn** [comment]
Same problem!
