### ISSUE TITLE
	Cannot setup port (for example 14 ) as input: Error: EINVAL: invalid argument, write

### ISSUE THREAD

**Issue by smartboart** [iobroker-community-adapters/ioBroker.rpi2#129]
rpi2.1 | 2022-08-29 12:49:18.336 | error | Cannot setup port 14 as input: Error: EINVAL: invalid argument, write
rpi2.1 | 2022-08-29 12:49:18.303 | error | Cannot setup port 15 as input: Error: EINVAL: invalid argument, write

Hello, i use the rpi2 Adapter on my multihost system.
Every host has its own instance of this adapter. one slave  host is connected to wlan and has this error message after rebooting  the host. 
In this case the inputs are not working.
As soon as i start the adapter again in the admin gui, it works.
This problem only accour if the slave host will be rebooted for its own. A reboot of the master host makes no trouble .

So it always needs a restart of the adapter after the slave host is rebooted.
a iobroker restart  - or iobroker stop and start - on the slave host do not lead into this problem.

I already implemented a delay in /lib/systemd/system/iobroker.service
ExecStartPre=/bin/sleep 30  which dely the startup of iob  after booting. Doesnt make any differnce.
Even  if i give all right recursive 0777 to the gpio folder /sys/class/gpio
makes no difference.

Repo latest / aktuell...
rpi2 v 1.3.2

System:
Raspi-Wall

    Plattform: linux
    RAM: 7.5 GB
    Node.js: v16.17.0
    NPM: 8.18.0
    Plattform: linux
    Betriebssystem: linux
    Architektur: arm
    CPUs: 4
    Geschwindigkeit: 1500 MHz
    Modell: ARMv7 Processor rev 3 (v7l)
    RAM: 7.5 GB
    System-Betriebszeit: 00:07:59
    Node.js: v16.17.0
    time: 1661760329048
    timeOffset: -120
    Adapter-Anzahl: 509
    NPM: 8.18.0
    Datenträgergröße: 58.4 GB
    Freier Festplattenspeicher: 45.7 GB
    Betriebszeit: 00:08:25
    Aktive Instanzen: 2
    Pfad: /opt/iobroker/
    aktiv:

**Comment by smartboart** [comment]
- <html><body>


  | 2022-08-29 13:12:59.835 | debug | stateChange  for rpi2.1.gpio.4.state found state =  {"val":true,"ack":true,"ts":1661771579823,"q":0,"from":"system.adapter.rpi2.1","user":"system.user.admin","lc":1651980491671}
-- | -- | -- | --
rpi2.1 | 2022-08-29 13:12:59.812 | debug | Written true into port 4
rpi2.1 | 2022-08-29 13:12:59.807 | debug | stateChange  for rpi2.1.gpio.4.state found state =  {"val":true,"ack":false,"ts":1661771579724,"q":0,"c":"script.js.common.Raumklima.Heizkreispumpe","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1651980491671}
rpi2.1 | 2022-08-29 13:12:31.345 | error | Cannot setup port 14 as input: Error: EINVAL: invalid argument, write
rpi2.1 | 2022-08-29 13:12:31.263 | error | Cannot setup port 15 as input: Error: EINVAL: invalid argument, write
rpi2.1 | 2022-08-29 13:12:29.551 | debug | stateChange for rpi2.1.gpio.27 found state = null
rpi2.1 | 2022-08-29 13:12:29.504 | debug | Register onchange handler
rpi2.1 | 2022-08-29 13:12:29.504 | debug | Port 17 directionCode: high
rpi2.1 | 2022-08-29 13:12:29.503 | debug | Port 17 direction: outhigh
rpi2.1 | 2022-08-29 13:12:29.502 | debug | Port 15 direction: in
rpi2.1 | 2022-08-29 13:12:28.270 | debug | stateChange for rpi2.1.gpio.26 found state = null
rpi2.1 | 2022-08-29 13:11:49.376 | debug | stateChange for rpi2.1.gpio.24.temperature found state = null
rpi2.1 | 2022-08-29 13:11:49.235 | debug | stateChange for rpi2.1.gpio.23.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:49.151 | debug | stateChange for rpi2.1.gpio.22.clicked_pressed found state = null
rpi2.1 | 2022-08-29 13:11:49.062 | debug | stateChange for rpi2.1.gpio.21.clicked found state = null
rpi2.1 | 2022-08-29 13:11:48.987 | debug | stateChange for rpi2.1.gpio.20.clicked_pressed found state = null
rpi2.1 | 2022-08-29 13:11:48.443 | debug | stateChange for rpi2.1.gpio.16.clicked found state = null
rpi2.1 | 2022-08-29 13:11:48.023 | debug | stateChange for rpi2.1.gpio.13.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.954 | debug | stateChange for rpi2.1.gpio.12.humidity found state = null
rpi2.1 | 2022-08-29 13:11:47.829 | debug | stateChange for rpi2.1.gpio.11 found state = null
rpi2.1 | 2022-08-29 13:11:47.720 | debug | stateChange for rpi2.1.gpio.10 found state = null
rpi2.1 | 2022-08-29 13:11:47.555 | debug | stateChange for rpi2.1.gpio.9.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.461 | debug | stateChange for rpi2.1.gpio.8.released found state = null
rpi2.1 | 2022-08-29 13:11:47.341 | debug | stateChange for rpi2.1.gpio.7.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.187 | debug | stateChange for rpi2.1.gpio.6.clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.043 | debug | stateChange for rpi2.1.gpio.4.humidity found state = null
rpi2.1 | 2022-08-29 13:11:46.879 | debug | stateChange for rpi2.1.gpio.3 found state = null
rpi2.1 | 2022-08-29 13:11:46.774 | debug | stateChange for rpi2.1.gpio.2 found state = null
rpi2.1 | 2022-08-29 13:12:29.502 | debug | Port 15 direction: in
rpi2.1 | 2022-08-29 13:12:28.270 | debug | stateChange for rpi2.1.gpio.26 found state = null
rpi2.1 | 2022-08-29 13:11:49.376 | debug | stateChange for rpi2.1.gpio.24.temperature found state = null
rpi2.1 | 2022-08-29 13:11:49.235 | debug | stateChange for rpi2.1.gpio.23.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:49.151 | debug | stateChange for rpi2.1.gpio.22.clicked_pressed found state = null
rpi2.1 | 2022-08-29 13:11:49.062 | debug | stateChange for rpi2.1.gpio.21.clicked found state = null
rpi2.1 | 2022-08-29 13:11:48.987 | debug | stateChange for rpi2.1.gpio.20.clicked_pressed found state = null
rpi2.1 | 2022-08-29 13:11:48.443 | debug | stateChange for rpi2.1.gpio.16.clicked found state = null
rpi2.1 | 2022-08-29 13:11:48.023 | debug | stateChange for rpi2.1.gpio.13.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.954 | debug | stateChange for rpi2.1.gpio.12.humidity found state = null
rpi2.1 | 2022-08-29 13:11:47.829 | debug | stateChange for rpi2.1.gpio.11 found state = null
rpi2.1 | 2022-08-29 13:11:47.720 | debug | stateChange for rpi2.1.gpio.10 found state = null
rpi2.1 | 2022-08-29 13:11:47.555 | debug | stateChange for rpi2.1.gpio.9.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.461 | debug | stateChange for rpi2.1.gpio.8.released found state = null
rpi2.1 | 2022-08-29 13:11:47.341 | debug | stateChange for rpi2.1.gpio.7.double_clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.187 | debug | stateChange for rpi2.1.gpio.6.clicked found state = null
rpi2.1 | 2022-08-29 13:11:47.043 | debug | stateChange for rpi2.1.gpio.4.humidity found state = null
rpi2.1 | 2022-08-29 13:11:46.879 | debug | stateChange for rpi2.1.gpio.3 found state = null
rpi2.1 | 2022-08-29 13:11:46.774 | debug | stateChange for rpi2.1.gpio.2 found state = null
rpi2.1 | 2022-08-29 13:12:29.502 | debug | Port 15 direction: in
rpi2.1 | 2022-08-29 13:12:29.491 | debug | Port 14 direction: in
rpi2.1 | 2022-08-29 13:12:29.489 | debug | Port 4 directionCode: high
rpi2.1 | 2022-08-29 13:12:29.488 | debug | Port 4 direction: outhigh
rpi2.1 | 2022-08-29 13:12:28.369 | debug | Buttons are pull down.
rpi2.1 | 2022-08-29 13:12:28.369 | debug | Inputs are pull down.


</body>
</html>

**Comment by Apollon77** [comment]
did you tried "iob fix"? Whats the other differences on this host? Kernel versions? All updates installed?

**Comment by smartboart** [comment]
Hello...yes i already tried iob fix..makes no differnce..my multihost System is realized with 3 identical rpi 4 qirh 8gb...all have the same Software and  operation System...Debian bester.. the difference is the wlan of the problem host...the others connected to the wirerd lan.

As i wrote is my repo latest and all adapters are alway up to date..
Thanks for your help...

**Comment by Apollon77** [comment]
I could not imagine that this comes from wlan ... But honestly ... sounds more like a forum topic because the error is coming from the system level ... so there is some kind of difference beside WLAN I assume ... maybe in node.js version, how it is installed or whatever

**Comment by smartboart** [comment]
The problem is i do not know when this started or if it was from the Beginning. I just recognized that my Button did not react and i started troubleshooting.. 
What is different to the adapter when it reconnects to the host after reboot of the host then to a manuell stop and start of the adapter afterwards?  It always needs a second stop start in this case...why does it work the second time...i mean after stop start..

**Comment by smartboart** [comment]
Remote gpio and fan setting is disabled in raspi-config

**Comment by Apollon77** [comment]
>  It always needs a second stop start in this case...why does it work the second time...i mean after stop start..

Then yes maybe some other systemd target does stuff in parallel to iobroker system run? maybe analyze the systemd starup scripts
