### ISSUE TITLE
CPU frequence not detected error

### ISSUE THREAD

**Issue by CoHoAppel** [iobroker-community-adapters/ioBroker.rpi2#17]
Installing ioBroker on a Rasp 4 . After installing the RPi Monitor the LOG file reports the following errors:
1)
host.raspberrypi4 | 2020-03-21 10:39:26.348 | error | Caught by controller[1]: cat: /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq: Permission denied   and
2)
rpi2.0 | 2020-03-21 10:39:30.507 | error | (5071) No Value found for cpu_frequency

Is the Rasp Pi model 4 not supported?

**Comment by Garfonso** [comment]
No, the problem is different, I think. In the past ioBroker used to be executed as root, but today it uses a more secure setup with its own iobroker user.
But it seems rpi2 adapter is not really suited for that... not sure how to fix that, right now.

**Comment by joergeli** [comment]
I've got the same error since nearly 1/2 year in ioBroker-Log:
**No Value found for cpu_frequency**
I can only fix it with this workaround, which changes user-pernissions.
**cd /sys/devices/system/cpu/cpu0/cpufreq
sudo chmod 777 cpuinfo_cur_freq**

But that's only a workaround and IMHO no solution to fix this problem finally.

**Comment by JoachimEngelmann** [comment]
The workaround from @joergeli works fine. The root problem is still present in version 1.2.0. Maybe it is possible to give iobroker user read permission for "/sys/devices/system/cpu/cpu0/cpufreq" at installation time or add a manual step to grand permissions and refer to it in the installation instructions?
If it is not possible to read the cpuinfo_cur_freq there shoulb maybe only a warning in the log and not an error
