### ISSUE TITLE
RPI2 adapter.objects.getObjectList is deprecated - Report to Developer!

### ISSUE THREAD

**Issue by FabianHM** [iobroker-community-adapters/ioBroker.rpi2#19]
Hello Developer,

please check the following Warning from the Log:

`
adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer! `

After every reboot the Log shows this Notice...
Thank you!

**Comment by joergeli** [comment]
I've got the same warning in ioBroker-Log after updating to js-controller 3.0.20:
**adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!**

**Comment by FabianHM** [comment]
If you need more Information, here is my Config:
JS controller, Installiert: 3.0.20
![grafik](https://user-images.githubusercontent.com/26110738/80861696-78416980-8c70-11ea-9f58-dd1ef338ed19.png)

**Comment by FabianHM** [comment]
Problem has been solved, Issue has been closed.
Thank you

**Comment by joergeli** [comment]
Nope,
warning is still there after every restart of rpi.2-Adapter

**Comment by joergeli** [comment]
Just updated to RPI-Monitor 1.2.0 and there is no warning anymore.
Thanks!
