### ISSUE TITLE
Upgrade to rpi-gpio@2 to support nodejs 10

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.rpi2#2]

**Comment by Apollon77** [comment]
maybe fixed by 1.1.0 ... awaiting Forum Feedback https://forum.iobroker.net/topic/23533/aufruf-rpi2-adapter-f%C3%BCr-nodejs-10

**Comment by foxriver76** [comment]
1.1.1 is stable but changelog missing, please add

**Comment by Apollon77** [comment]
done
