### ISSUE TITLE
GPIOs not working in Version 1.2.0

### ISSUE THREAD

**Issue by daum1988** [iobroker-community-adapters/ioBroker.rpi2#22]
I updated to 1.2.0, after that the GPIOs of my Raspberry Pi are no longer working.
I can't set outputs and Input States don't change.

**Comment by Apollon77** [comment]
What does log say? Do you also updated nodejs?

**Comment by daum1988** [comment]
nodejs is on Version 12.16.3
The log says (4626) GPIO is not initialized!

**Comment by Apollon77** [comment]
Did you updated nodejs? Which js-Controller you have running?

**Comment by daum1988** [comment]
Yes I did update nodejs from 10.20 to 12.16.3.
The JS-Controller is on Version 3.0.20

**Comment by Apollon77** [comment]
Try „iobroker rebuild rpi2 --install“. Works then?

**Comment by daum1988** [comment]
No that did't help.
I also tried to completely uninstall rpi2 and reinstall it and that didn't help.

**Comment by Apollon77** [comment]
ok, open a shell, go to the iobroker dir

cd node_modules/iobroker.rpi2
npm install --production

Please post outpu here

**Comment by daum1988** [comment]
`pi@pool:/opt/iobroker/node_modules/iobroker.rpi2 $ npm install --production
audited 472 packages in 5.179s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@pool:/opt/iobroker/node_modules/iobroker.rpi2 $ npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/glob-watcher/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 455 packages from 619 contributors in 14.958s

18 packages are looking for funding
  run `npm fund` for details

fixed 0 of 2 vulnerabilities in 472 scanned packages
  2 vulnerabilities required manual review and could not be updated`

**Comment by daum1988** [comment]
Thats the output

**Comment by Apollon77** [comment]
In fact I did not said you should use "audit fix" but ok lucky seems not to have broken things.

And it still does noch work?

Ok then the hard way.

There should be (start in iobroker dir) a node_modules/rpi-gpio/ and/or node_modules/iobroker.rpi2/node_modules/rpi-gpio check and run "npm rebuild" there

**Comment by daum1988** [comment]
I didn't have the time to test if the last step fixed my problem.
Just tested it and it seems to be working like normal again after the "npm install --production"

**Comment by daum1988** [comment]
Thanks for your help
