### ISSUE TITLE
[Responsive Design] Please add size attributes to jsonConfig

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.rpi2#227]
Thanks for migrating to jsonConfig.
**Please check the brand new jsonConfig in respect to responsive design.**

At a first glance all size attributes are missing (xs/sm/md/lg/xl). Please add.
Please check usability with differnet screnn resolutions, especially small ones.

@simatec can answer more questions / provide tipps to make the new jsonConfig UI Responsive Design ready from the start.

**Comment by Garfonso** [comment]
fixed by 17dd5d6df4640fa03c30a4ab3ef39c28b7f669c4
