### ISSUE TITLE
Software debounce GPIO IN 

### ISSUE THREAD

**Issue by Smallfeuer** [iobroker-community-adapters/ioBroker.rpi2#30]
My Problem is, that i want to reduce the Traffic from Slave to Master System, if the button in the slave sytem bounce. For every Input i need two resistance and one capacitor. If somebody can write a short programm to debounce the gpio with time x in ms. This was very helpful. Hope you understand ;)

**Comment by raintonr** [comment]
Absolutely required.

IMHO this change goes hand in hand with implementation of push button detection with click, long press, double tap, etc. Looks like this library would do all the heavy lifting:

https://www.npmjs.com/package/rpi-gpio-buttons

Could be implemented by adding 'button' to the 'type' dropdown on the GPIOS settings tab.

**Comment by raintonr** [comment]
Looks like this was fixed with #48
