### ISSUE TITLE
Where to configure the RPI's addresses

### ISSUE THREAD

**Issue by Jade64** [iobroker-community-adapters/ioBroker.rpi2#36]
I found no field in the config, where to input the IP address of the RPI which I want to access. I have several of them in the network.
Or is this adapter only for the scenario, where iobroker is installed on the RPI that is meant here?
Then I cannot use it because the iobroker is running on a different hardware (SAN).

**Comment by Apollon77** [comment]
This adapter works local ... so install it on the raspi directly. No "remote" usage possible
