### ISSUE TITLE
Bump Version for release

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.rpi2#49]
To release #30, #31, #44, #47, #45... and probably more ;)

**Comment by raintonr** [comment]
@Apollon77 ... what version do you prefer for the next release? Possibly 1.3.0 as there will be quite a number of changes in there.

Alternatively... do you prefer to make a number of smaller releases with less change in each?

**Comment by Apollon77** [comment]
1.3.0 in normal cases, if something is breaking we would be at 2.0.0
