### ISSUE TITLE
error on Raspberry Pi 4

### ISSUE THREAD

**Issue by Moormerlander** [iobroker-community-adapters/ioBroker.rpi2#5]
Get this error in my Log on my Raspi 4:

> No Value found for cpu_frequency

**Comment by backfisch88** [comment]
Same!

**Comment by fliix-de** [comment]
Looks like a permission problem?

/var/log/syslog:
`bash[510]: cat: /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq: Permission denied`

**Comment by Apollon77** [comment]
And the workaround is the only solution! Some such system infos are only readable by the "real root" user ...
