### ISSUE TITLE
with js-controller 3.3.2 there are warnings wrong type for objects

### ISSUE THREAD

**Issue by SurfGargano** [iobroker-community-adapters/ioBroker.rpi2#72]
with js-controller 3.3.2 there are warnings wrong type for objects.
e.g
State value to set for "rpi2.0.cpu.load1" has wrong type "string" but has to be "number"

**Comment by KayThe95** [comment]
Bei mir ebenso. Gibt es dafür einen Workaround? Ist ja bei mehreren Adaptern so.

**Comment by marlan99** [comment]
Wird dieser Adapter noch weiterentwickelt?
Ich hoffe ebenfalls auf die Behebung dieses Bugs

**Comment by Apollon77** [comment]
@marlan99 Why you assume there is no development? Just because 12 days went by and it was not fixed?

**Comment by Apollon77** [comment]
PS: It is just a warning and bo bug per se

**Comment by marlan99** [comment]
Sorry when it was somehow rude.
Its just a lack of knowledge on my side. 

Thx for your feedback

**Comment by ente34** [comment]
```

Got the same info messages after updating js-controller

<!--StartFragment-->
rpi2.0 | 2021-05-30 11:06:45.627 | info | (5290) State value to set for "rpi2.0.cpu.load15" has to be type "number" but received type "string"
-- | -- | -- | --
rpi2.0 | 2021-05-30 11:06:45.626 | info | (5290) State value to set for "rpi2.0.cpu.load5" has to be type "number" but received type "string"
rpi2.0 | 2021-05-30 11:06:45.625 | info | (5290) State value to set for "rpi2.0.cpu.load1" has to be type "number" but received type "string"
&nbsp;

<!--EndFragment-->


```

**Comment by Apollon77** [comment]
Can you pleas etry GitHub version? Install from GitHub and restart adapter manually please

**Comment by luieiob** [comment]
[debug.log](https://github.com/iobroker-community-adapters/ioBroker.rpi2/files/6832666/debug.log)

**Comment by Apollon77** [comment]
Helped a lot ... can you please install GitHub version ad try again? (Install and restart manually afterwards)

**Comment by luieiob** [comment]
no more errors, thanks
