### ISSUE TITLE
GPIO Eingang als Taster mit externen Pullup 

### ISSUE THREAD

**Issue by e-i-k-e** [iobroker-community-adapters/ioBroker.rpi2#86]
Hallo, 

nach einem Update von 1.20 auf 1.3.0/1.3.1 habe ich Probleme mit den als Eingang deklarierten GPIO.  
An den Eingängen sind Taster verbaut, die Pins haben ein festes Potential mit einem Pullup (10k). 

Nach dem Update sind die Eingänge sehr träge (oder unempfindlich?) - ich muss min. zwei mal Tasten, bis dies erkannt wird. 
Dieses verhalten habe ich an 5 Slave Systeme (Raspberry Pi 3b).

Ein Downgrade auf 1.2.0 beseitigt erstmal das Problem.

**Comment by Apollon77** [comment]
@raintor Any idea?

**Comment by fetzz-de** [comment]
Bei mir ist das Fehlerbild identisch!

**Comment by innriver** [comment]
Hallo,
ich habe noch mal mit Version 1.3.1 getestet: Wenn nur ein Eingang sich ändert funktioniert die Weiterleitung meistens. Werden aber gleichzeitig mehrere Eingänge geändert wird fast immer nur ein Eingang in iobroker mit dem richtigen state angezeigt. Bei der Abfrage mit "pigs" auf dem Raspberry wird alles korrekt angezeigt. Nach Neustart des GPIO-Adapters werden alle states richtig dargestellt. Bei der Version 1.2.0 tritt der Fehler nicht auf! Die Tests wurden direkt an den Ports des Raspberry, also ohne lange Leitungen, ausgeführt. Auch wurde der Raspberry 3B plus ohne Erfolg gewechselt. Kann man mit einer Fehlerbehebung rechnen?

Gruß Wolfgang

**Comment by e-i-k-e** [comment]
Hallo zusammen,

würde mich auch sehr interessieren, da man vermutlich früher oder später auf eine neue Version aktualisieren muss.

**Comment by Basti-NRW** [comment]
Hallo, ich habe gerade das selbe Problem, die Eingänge reagieren träge oder garnicht. Eine schnelle Lösung wäre schön. Mit welcher Version funktioniert es denn noch zuverlässig?
Ich nutze dieVersion v1.3.2
MfG

**Comment by JR-Home** [comment]
Hallo Zusammen, das Problem kann ich bestätigen. Ab Version 1.3.x wird eine Änderung an den GPI Eingängen nicht mehr zuverlässig erkannt. Auch die Einstellung der Filterzeiten von 0...100 ändert an dem Verhalten nichts. Nach einem Downgrade auf Version 1.2.0 funktioniert alles wieder wie erwartet!
Bitte Problem lösen...

**Comment by Apollon77** [comment]
@raintonr Do you have any clue here? 1.3.0 ist mostly based on your changes and a lot of PRs from you

**Comment by JR-Home** [comment]
Additional infos about my observed behaviour. Im using IOBroker with RPI-Monitor on an Raspberry 3b. In my application I have a pushbutton from GPI 19 to 3.3V, with an external pulldown resistor. In RPI-Monitor Version 1.3.0, 1.3.1 and 1.3.2 the signal change is not detected in all cases. E.g. pressing the button the input changes from 0 to 1 as extepcted, but when releasing the button, the signal stays at high. If I press the pushbutton again, in most cases the new change is beeing detected and the input changes after releasing to low again. After downgrade to Version 1.2.0 a singal change is being detected in all cases reliable. if you have any further questions please let me know.

**Comment by Apollon77** [comment]
Please try to change loglevel of the instance to "debug" and see if this brings more insights?

**Comment by JR-Home** [comment]
Messages after activating loglevel debug with RPI-Monitor Version 1.3.2. The first Button press and release was detected as expected, after the second press, the release of the Button (0V) was not handled.

Button an Port 19 betätigt (3.3V)
2022-04-25 19:24:17.969 - debug: rpi2.0 (2519) GPIO change on port 19: true
2022-04-25 19:24:18.022 - debug: rpi2.0 (2519) GPIO debounced on port 19: true
2022-04-25 19:24:18.039 - info: javascript.0 (1027) script.js.common.Motion: Shutdow Button pressed... (Message of my script)
2022-04-25 19:24:18.042 - debug: rpi2.0 (2519) stateChange for rpi2.0.gpio.19.state found state = {"val":true,"ack":true,"ts":1650907458032,"q":0,"from":"system.adapter.rpi2.0","user":"system.user.admin","lc":1650907458032}

Button an Port 19 losgelassen (0V) -> Low Level wurde korrekt erkannt...
2022-04-25 19:24:18.635 - debug: rpi2.0 (2519) GPIO change on port 19: false
2022-04-25 19:24:18.686 - debug: rpi2.0 (2519) GPIO debounced on port 19: false
2022-04-25 19:24:18.695 - info: javascript.0 (1027) script.js.common.Motion: Shutdown Button released, but only short time...1s (Message of my script)
2022-04-25 19:24:18.697 - debug: rpi2.0 (2519) stateChange for rpi2.0.gpio.19.state found state = {"val":false,"ack":true,"ts":1650907458692,"q":0,"from":"system.adapter.rpi2.0","user":"system.user.admin","lc":1650907458692}

Button an Port 19 betätigt (3.3V)
2022-04-25 19:24:21.014 - debug: rpi2.0 (2519) GPIO change on port 19: true
2022-04-25 19:24:21.068 - debug: rpi2.0 (2519) GPIO debounced on port 19: true
2022-04-25 19:24:21.084 - info: javascript.0 (1027) script.js.common.Motion: Shutdow Button pressed... (Message of my script)
2022-04-25 19:24:21.090 - debug: rpi2.0 (2519) stateChange for rpi2.0.gpio.19.state found state = {"val":true,"ack":true,"ts":1650907461080,"q":0,"from":"system.adapter.rpi2.0","user":"system.user.admin","lc":1650907461080}

Button an Port 19 losgelassen (0V) -> FEHLER !!! Level 0 wurde nicht in den Object Status übernommen !!!
2022-04-25 19:24:22.360 - debug: rpi2.0 (2519) GPIO change on port 19: true      Hint: different from previous release!!!
2022-04-25 19:24:22.363 - debug: rpi2.0 (2519) GPIO change on port 19: false

**Comment by raintonr** [comment]
What have you got this configured as? A button or simply an input?

![image](https://user-images.githubusercontent.com/3794098/165145140-c1bf2e2f-828f-47a4-bb9c-e97f679fa6ce.png)

**Comment by JR-Home** [comment]
Configured as a simple input.

**Comment by raintonr** [comment]
Why? If it's a pushbutton, configure it as one.

**Comment by JR-Home** [comment]
It was not transparent for me what the functionality of a configured pushbutton is. So i used it as simple input as before with old version of RPI-Monitor....

**Comment by Basti-NRW** [comment]
Ich habe mal verschiedene Einstellungen getestet und bin zu keinem zufrienenstellenden Ergebnis gekommen.
Mein Aufbau besteht aus 16 Alarmlinien die über Optokoppler immer geschlossen sind. Die Alarmlinien sind auf den GPIO`s 5,6,12,13,16,17,18,19,20,21,22,23,24,25,26,27. Alle mit 10k Pullup. Wenn ich mehr als 4 GPIO´s benutze und alle gleichzeitig trenne, wird dieses nicht an allen GPIO´s erkannt. Wie muss ich alles einstellen damit es funktioniert?

**Comment by raintonr** [comment]
I have 4 switches and 3 door sensors, all through optocouplers and they all work just fine. One thing to note is that most optocoupler boards already include a resistor so you don't need to add your own pull-up.

If you think this isn't working, you need to turn describe what's happening in every detail. Then turn debug on and share some messages that can help identify the problem.

**Comment by Apollon77** [comment]
@Basti-NRW Kannst Du bitte in englishch schreiben? @raintonr kann kein Deutsch :-)

**Comment by Basti-NRW** [comment]
How do I have to adjust everything? What is the difference between input and button? I just want to evaluate the status False or True.
![1](https://user-images.githubusercontent.com/104160907/165497888-fa18279c-f5e7-418c-acc1-bd50745ca530.jpg)
![2](https://user-images.githubusercontent.com/104160907/165497895-6e3fb238-9108-40e6-bb31-833ef31c84aa.jpg)

Thanks for your help

**Comment by raintonr** [comment]
> What is the difference between input and button?

Look in the objects created for the input. Button creates objects that are triggered on single/double press/press/release, etc. Input just has a single state.

**Comment by Basti-NRW** [comment]
if "Buttons are wired pull up" is marked, does it mean that I have pulled the button up or that the Raspberry is setting the internal pullups? 
Is the problem maybe with my Raspberry Pi 2 Model B?
What debounce time is practical?

**Comment by raintonr** [comment]
> if "Buttons are wired pull up" is marked, does it mean that I have pulled the button up or that the Raspberry is setting the internal pullups?

It just inverts the logic.

> Is the problem maybe with my Raspberry Pi 2 Model B?

I have no idea. I suggest you get some test program outside of IoB and make sure your inputs are doing what you want.

> What debounce time is practical?

It's debounce logic. Time for the signal to settle.
