### ISSUE TITLE
 Steer/monitor another Raspi

### ISSUE THREAD

**Issue by Pedder007** [iobroker-community-adapters/ioBroker.rpi2#92]
**Is your feature request related to a problem? Please describe.**
Hi all,
having here running _some_ Raspis, and I guess I'm not the only one with more than one device for different purposes, but only one with ioBroker, I have asked myself, if it would be feasible, to use the adapter also for steering, or in minimum monitoring, another PI in the same network?
Thus it might (I have no clue if that is doable with a moderate effort?) be an idea, to use this adapter, surely respectively configurable, for additional PIs?

**Describe the solution you'd like**
I would be happy to get the possibility to monitor, or maybe also steer (GPIOs), another PI remotly from my ioBroker PI.

**Describe alternatives you've considered**
I found a couple of other monitoring tools in the net, but they are mostly too complex, run an own additional web server, and would also have to be however make accessible for ioBroker.

**Additional context**
If it is a stupid idea, please don't laugh about. I then will directly close my request ;-)

**Comment by Apollon77** [comment]
Just install iobtoker and this adapter on these hosts as slave and connect to master iobroker ... ?!

**Comment by Pedder007** [comment]
Hi @Apollon77, I already came along that idea myself 😉
But I thought, that it might not necessarily be the most optimal idea, to install everywhere a full ioBroker; on my motionPI, on my DNS/PiholePI, …
Thus I gave it a try here. But as written, if this isn‘t an option, I will call back my request 😊

**Comment by Pedder007** [comment]
@Apollon77 Hi again, as my Mutlihost Setup now is running, I tested a bit around.
What I saw is, that the 'Info' adapter seems not beeing able to run multi instances, resp. allthough info was running on one of my slaves before connecting him to the master, I'm now not able to access the respective belonging objects.
Is there a way to read this data from the master?

**Comment by Apollon77** [comment]
I do not understand your words ... can you schow a screenshot or such?

**Comment by Pedder007** [comment]
Hi nochmal, ich springe einfach mal ins Deutsche 😊
Also, ich wollte mir in ioBroker eine kleine Überwachung für zwei meiner weiteren Raspis bauen. Auf dem einen läuft Motioneye, was mit zwei HD Cams recht rechenintensiv ist und mein DNS Server steht im Heizungskeller, wo es immer sehr warm ist.
Nun habe ich mein Setup als Master/Slave Setup konfiguriert und dachte, dass ich dann über den Master auch an alle Objekte auf den Slaves herankomme, welche es dort gibt.
Leider scheint das aber nicht für den Info-Adapter zu gelten, welcher ja genau meine benötigten Überwachungsparameter ( CPU load (%), Temperatur, etc) enthalten würde.
Als Minimallösung gäbe es noch den RPI-Monitor, welcher aber auch erst zu Multihost überredet werden muss….

**Comment by Apollon77** [comment]
Was genau hast Du gebaut?  Slaves von ioBroker haben keine eigenen Daten, da Die nur auf dem Master liegen. Der Slave verbindet sich zum Master und nur der hat alle Daten. Was genau hast Du aufgsetzt und wie? Einfach weiterer Host einzeln? Oder auch mit "multihost"? bzw setup custom?

**Comment by Pedder007** [comment]
Hallo, ich habe einfach ioBroker auf z. B. den Motioneye Raspi nachinstalliert und nachdem der lief, diesen lt. Anleitung in einen Slave umgewandelt und mit dem Master verbunden. Der Info 'Adapter' war aber standardmäßig bereits auch darauf installiert, was ich noch gesehen hatte, sonst aber auch nichts.

**Comment by Apollon77** [comment]
Ok, dann kurz verständnisklärung: Wenn der Host zum Slave wird ist er wieder "jungfräulich"! Der Master kontrolliert alles.

bedeutet: Du öffnest Master-Admin und wählst dort oben deinen Slave Host aus. Dann installierst Du da den info adapter.

Es ist korrekt das in dem Fall die Files von Info und Admin schon da sind und ggf nur noch eine Instanz erstellt werden muss. Und dann geht das alles.
Du kannst aber auch einfach direkt den rpi2 Adapter auf den Slave machen. Und dann hast Du eine neue Instanz und die hat dann die Daten des Slaves

**Comment by Pedder007** [comment]
Oha, darauf muss man kommen. Ich hatte den schmalen Auswahlrahmen glatt übersehen und mich schon gefragt, wie ich generell auch alle anderen Adapter auf den unterschiedlichen Raspis manage...  DANKE!
Nun fällt mir auf, dass ich es wohl bei meinem ersten Master-Slave Versuch, bei welchem hinterher Master und Slave vertauscht waren, wohl geschafft habe, dass dann auf den Slave tatsächlich sämtliche Adapter übernommen wurden.
Bei meinem zweiten Slave, sind dann nur noch ein paar drauf. Ich denke ich werden den ersten nochmals aus dem Verbund heraus nehmen (ist ohnehin nur ein Testsystem) und diesen dann erst einmal bereinigen ...;-)
Wenn es danach noch Fragen gibt, melde ich mich nochmal.
Danke nochmal :-)

**Comment by Apollon77** [comment]
Ehrloch ... du kannst auf den slave gehen und dort in /opt/iobroker einfach "npm uninstall iobroker.name-von-zuviel" machen und so die adadpter runterwerfen. oder lässt Sie drauf ... am ende egal. Bekommst nur ggf Updates angezeigt. Ohne ne Instanz fressen die nur bissl Plattenplatz

**Comment by Pedder007** [comment]
Tja leider, ich hatte das nicht gesehen und habe immer Instanzen hinzugefügt (z. B. RPI-Monitor) und diese dann manuell auf einen der Slave Hosts umgestellt. Der Test-Slave ist jetzt bereinigt und funzt so (denke ich) wie er soll und ich finde auch die Info-Objekte der Slaves auf dem Master :-)
Etwas verwirrend finde ich, dass man die Adapter über den Auswahlknopf lediglich für die entsprechenden Hosts angezeigt bekommt, dies so aber in der Instanzen- und Objekte-View nicht der Fall ist. Die sind immer alle zu sehen. Ich denke die anderen Views sollten auch filtern, dann hätte man etwas mehr Übersicht, insbesondere bei den Objekten. Man könnte ja theoretisch auch jeweils eine View mit allen hinzufügen. 
Meinst Du es lohnt dazu einen Request zur Admin-Oberfläche einzustellen?
Dir auf jeden Fall nochmal Danke und Grüße
Peter

**Comment by Apollon77** [comment]
> Ich denke die anderen Views sollten auch filtern, dann hätte man etwas mehr Übersicht, insbesondere bei den Objekten. 

Ich glaube das behindert in der bedienung ungemein bzw wäre von der Usebiloity nicht ideal. Nur "Adapter" Tab filtert

**Comment by Pedder007** [comment]
... hat sich ja mit meine 'Edit' quasi erledigt ;-)
